
:url-bmw-frame-gussets: https://www.advrider.com/f/threads/bmw-frame-gussets.638795/
:url-frame-gussets-svg: https://github.com/moto-design/bmw-frame-gussets


:imagesdir: images

:notitle:
:nofooter:

= ORGS Build Up - Page 12

[big]*The ORGS Build Up Project*

*Page 12*

*naginalf, Nov 12, 2012:*

Stagehand said:

You, sir.

I want to ride with You.

Nice videos mate Click to expand...

+2 :eek1 Thanks for posting, that made my day!

*Prutser, Jul 22, 2013:*

I'm wondering how this bike is doing now ?

x3300 are you still happy with all the mods. Or did you improve more things ?

*Ras Thurlo, Jul 23, 2013:*

Prutser said:

I'm wondering how this bike is doing now ?

x3300 are you still happy with all the mods. Or did you improve more things ? Click to expand...

Great bike, great clips

*b0mb3r, Apr 19, 2014:*

Any hi res pictures of the bike ... with the HPN tank on it

*igormortis, Jul 9, 2015:*

Still one of my favorite bikes. Since we haven't heard anything in a while, I can only hope that he's too busy riding.

*hardwaregrrl, Jul 9, 2015:*

Whoa.....Thread from the Dead!

I heard he and the G/S had a bad "off" and he and the bike were immobile for a bit. Heres to hoping he's on the mend!!!

*fishkens, Jul 9, 2015:*

Nice bump. One of the best builds ever. Hope all is well.

*igormortis, Jul 9, 2015:*

Not what I wanted to hear, but thanks for the update. Hopefully we see both of them rolling again soon!

*pdny, Jul 10, 2015:*

Hope he's ok. Epic thread and build - someone needs to make a few of these bikes I have a stock PD and have always wanted something with more 'legs'.

J

*rediRrakaD, Aug 16, 2015:*

I bumped into x3330 yesterday at Hollister Hills OHV! He's fine. Broke a collarbone earlier this year, was out riding a MX bike yesterday... talented rider!

ORGS is fine (don't know if he was on that when the break occurred), had an oil cooler leak and that's now solved.

hardwaregrrl you may have me confused with him... I was working with him on his "HPN" style frame bracing a while back... I had a rather bad get off (well, the landing sucked) and shattered my fib/tib/tib plateau. Took a solid year and a half to recover. I'll be finishing up the bracing and my GS build later this year. Went on hold due to the accident, wife divorcing me, and having to move. Fun stuff.

This build certainly was an inspiration to many.

*hardwaregrrl, Jun 7, 2016:*

I wish these pics were still available.....anybody still talk to Geoff? Was hoping to take a peek at the frame gussets.

*Box'a'bits, Jun 7, 2016:*

The pics are still there. Just drag your cursor over the https//###.jpg between the "##", then get the picture to come up in a different tab. Slow, but you should be able to recover what you want. Context can be found from the text surrounding the pictures

*rediRrakaD, Jun 7, 2016:*

i can take more pics when I return from IOMTT...

*igormortis, Jun 8, 2016:*

Thread is aliiive! Woo!

*hardwaregrrl, Jun 8, 2016:*

A-ha! Wondering if anyone besides redi printed and used his frame gussets he so generously shared with us.?

*hardwaregrrl, Jun 8, 2016:*

rediRrakaD said:

i can take more pics when I return from IOMTT... Click to expand...

I'd love to see some more pics of your bike! My frame is being straightened and they wanted to send templates to the water jet guy. I sent Geoff's drawings to them and wanted to show them pics of his frame....thx!

*Screaming Chicken, Jun 8, 2016:*

Even with shipping, won't it be cheaper to just buy a set? SWT has a reasonable set of frame bracing bits for €120.

*hardwaregrrl, Jun 8, 2016:*

Screaming Chicken said:

Even with shipping, won't it be cheaper to just buy a set? SWT has a reasonable set of frame bracing bits for €120. Click to expand...

It's very reasonable but not complete. It lacks the rear shock mounts on the swing arm and the main frame, and the HPN tank mounts. Manuel is out till the 22nd of June and won't be shipping out till he gets back. Frame guy is ready to weld my bike by then.

*Heipaal, Nov 19, 2016:*

Pictures don't show for me anymore, if you want to see them (and you should, lots of info!) follow this link and click what you wanna see:

*dap spackled, Nov 19, 2016:*

Please do not show. NO SHOW = no inspiration.

It will save me money in the long run!


*NOTICES*

All ORGS design materials are relesed under the Fabricators Design License.

Copyright x3300
